# Generated by Django 4.1.7 on 2023-03-28 19:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_comments_comment_rename_likes_like'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_alter_follows_follower_id_alter_follows_following_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Accounts',
            new_name='Account',
        ),
    ]
