# Generated by Django 4.1.7 on 2023-05-16 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_mediapost'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediapost',
            name='page_num',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='mediapost',
            name='content_url',
            field=models.ImageField(default='images/users/profiles/default/default.png', max_length=200, upload_to='images/users/profiles/'),
        ),
    ]
