# Generated by Django 4.1.7 on 2023-05-31 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_mediapost_page_num_alter_mediapost_content_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediapost',
            unique_together={('post_id', 'page_num')},
        ),
    ]
