# Generated by Django 4.1.7 on 2023-03-28 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follows',
            name='follower_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower_id', to='posts.accounts'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='following_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='following_id', to='posts.accounts'),
        ),
    ]
