# Generated by Django 4.2.5 on 2023-10-02 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_uuidbasedtag_alter_post_tags'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uuidbasedtag',
            table='post_tags',
        ),
    ]
