# Generated by Django 4.2.5 on 2023-10-02 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_uuidbasedtag_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uuidbasedtag',
            options={'verbose_name': 'posts_tags'},
        ),
        migrations.AlterModelTable(
            name='uuidbasedtag',
            table='posts_tags',
        ),
    ]
