# Generated by Django 4.1.7 on 2023-05-14 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaprofile',
            name='content_url',
        ),
        migrations.AddField(
            model_name='mediaprofile',
            name='profile_image',
            field=models.ImageField(default='images/users/profiles/default.png', max_length=200, null=True, upload_to=''),
        ),
    ]
