# Generated by Django 4.1.7 on 2023-05-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_mediaprofile_content_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaprofile',
            name='profile_image',
            field=models.ImageField(default='images/users/profiles/default.png', max_length=200, null=True, upload_to='images/users/profiles/'),
        ),
    ]
