# Generated by Django 4.1.7 on 2023-05-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_mediaprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_seen_posts',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
