# Generated by Django 4.1.7 on 2023-07-06 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_story_user_id_mediastory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='last_seen_posts',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='content_url',
            field=models.ImageField(default='static/images/stories', max_length=200, upload_to='static/images/users/story/default.png'),
        ),
        migrations.DeleteModel(
            name='MediaStory',
        ),
    ]
