version: "3.8"
services:
  redis:
    image: redis:6.0.9-alpine
    ports:
      - 7000:6379
  backend:
    build: 
      context: .
      dockerfile: .
    ports:
      - 8000:8000
    volumes:
      - static_volumes:/django/static
  nginx:
    build: 
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volumes:/etc/nginx/static

volumes:
  # represents the data which is shared between the nginx server and the wsgi django server
  static_volumes:
  


