# Generated by Django 4.1.7 on 2023-08-15 19:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMessage',
            fields=[
                ('message_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[(1, 'post_message'), (2, 'text_message')], max_length=50)),
                ('is_read', models.BooleanField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('members', models.ManyToManyField(to='accounts.account')),
            ],
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=600)),
                ('message_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.basemessage')),
            ],
        ),
        migrations.CreateModel(
            name='PostMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.basemessage')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.chat')),
            ],
        ),
        migrations.AddField(
            model_name='basemessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat'),
        ),
        migrations.AddIndex(
            model_name='basemessage',
            index=models.Index(fields=['message_type', 'chat'], name='chat_baseme_message_72bfe9_idx'),
        ),
    ]
