# Generated by Django 4.1.7 on 2023-08-26 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchat',
            old_name='chat_id',
            new_name='thread',
        ),
        migrations.RenameField(
            model_name='privatechat',
            old_name='chat_id',
            new_name='thread',
        ),
    ]
