# Generated by Django 4.1.7 on 2023-09-01 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='privatechat',
            unique_together=set(),
        ),
    ]
