# Generated by Django 4.1.7 on 2023-09-01 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('chat', '0002_alter_privatechat_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechat',
            name='member1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member1', to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='member2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member2', to='accounts.account'),
        ),
        migrations.AlterUniqueTogether(
            name='privatechat',
            unique_together={('member1', 'member2')},
        ),
    ]
